[project]
name = "taxi-prediction-fullstack-andreas-johansson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.2",
    "setuptools>=80.9.0",
    "streamlit>=1.49.1",
    "uvicorn>=0.35.0",
]
